# wrangler.toml
name = 'hansterhorst'
compatibility_date = "2025-07-31"

[[routes]]
pattern = "hansterhorst.com"
custom_domain = true

[build]
command = "hugo"

[assets]
directory = "./public"
not_found_handling = "404-page"
