# wrangler.toml
name = 'hansterhorst'

[[routes]]
pattern = "hansterhorst.com/*"
custom_domain = true

[[routes]]
pattern = "www.hansterhorst.com/*"
custom_domain = true

[build]
command = "hugo"

[assets]
directory = "./public"
not_found_handling = "404-page"
